# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: ubb_iss_homepage
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        chain_provider:
            chain:
                providers: [main, in_memory]
        main:
            entity: { class: UbbIssBundle\Entity\User, property: username }
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }
    encoders:
        UbbIssBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext
