ubb_iss_homepage:
    path:     /
    defaults: { _controller: UbbIssBundle:Default:index }

ubb_iss_show_student_grades:
    path:     /grades
    defaults: { _controller: UbbIssBundle:Default:showGrades }

ubb_iss_add_student_grades:
    path:     /add_grades/line={line}&SubName={SubName}&SpecName={SpecName}&Group={Group}
    defaults: { _controller: UbbIssBundle:Default:addGrades }

ubb_iss_study_lines:
    path:     /specs/SubName={SubName}&SpecName={SpecName}
    defaults: { _controller: UbbIssBundle:Default:getSpecializationLines }

ubb_iss_group:
    path:     /group/line={line}&SubName={SubName}&SpecName={SpecName}
    defaults: { _controller: UbbIssBundle:Default:getGroups }

ubb_iss_show_teacher_activities:
    path:     /activities
    defaults: { _controller: UbbIssBundle:Default:getActivities }

ubb_iss_edit_student_grades:
    path:   /edit_grades
    defaults: { _controller: UbbIssBundle:Default:editGrades}

ubb_iss_show_contracts:
    path: /show_contracts
    defaults: { _controller: UbbIssBundle:Default:showContracts}

ubb_iss_edit_contract:
    path: /edit_contract/{contractId}
    defaults: {_controller: UbbIssBundle:Default:editContract}

add_contract_subjects:
    path: /add_subject
    defaults: {_controller: UbbIssBundle:Default:addSubject}

remove_contract_subjects:
    path: /remove_subject
    defaults: {_controller: UbbIssBundle:Default:removeSubject}

ubb_iss_change_pass:
    path:     /change_password
    defaults: { _controller: UbbIssBundle:Default:changePassword }

ubb_iss_edit_pass:
    path:     /change_password_action
    defaults: { _controller: UbbIssBundle:Default:editPassword }