ubb_iss_homepage:
    path:     /
    defaults: { _controller: UbbIssBundle:Default:index }

ubb_iss_show_student_grades:
    path:     /grades
    defaults: { _controller: UbbIssBundle:Default:showGrades }

ubb_iss_add_student_grades:
    path:     /add_grades/{SubName}
    defaults: { _controller: UbbIssBundle:Default:addGrades }

ubb_iss_show_teacher_activities:
    path:     /activities
    defaults: { _controller: UbbIssBundle:Default:getActivities }