UbbIssBundle\Entity\Activity:
    type: entity
    table: activities
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 255
        hoursPerWeek:
            type: integer
    manyToOne:
        teacher:
            targetEntity: Teacher
            inversedBy: activities
            joinColumn:
                name: teacher_id
                referencedColumnName: id
        subject:
            targetEntity: Subject
            inversedBy: activities
            joinColumn:
                name: subject_id
                referencedColumnName: id
