UbbIssBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
    oneToOne:
        student:
          targetEntity: Student
          joinColumn:
            name: student_id
            referencedColumnName: id
            nullable: true
        teacher:
          targetEntity: Teacher
          joinColumn:
            name: teacher_id
            referencedColumnName: id
            nullable: true
